# Generated by Django 2.2.16 on 2023-03-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230227_1446'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='uq_user_author'),
        ),
    ]
